name: Build EXE on push

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: windows-latest  # щоб зібрати .exe

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install pyinstaller
      run: |
          pip install -r requirements.txt
          pip install pyinstaller

    - name: Build .exe file
      run: pyinstaller --onefile --noconsole --icon=KMR.ico --paths=. smartcat_gui.py

    - name: Upload artifact (exe)
      uses: actions/upload-artifact@v4
      with:
        name: my-exe
        path: dist/smartcat_gui.exe